### ISSUE TITLE
Load Disqus comments without explicit protocol

### ISSUE THREAD

**Issue by thethomaseffect** [daveyarwood/daveyarwood.github.io#1]
Comments fail to load under https, solution is to change `http://emptyorchestra.disqus.com/embed.js` to `//emptyorchestra.disqus.com/embed.js`

```
[blocked] The page at 'https://daveyarwood.github.io/2014/07/30/20-cool-clojure-functions/' was loaded over HTTPS, but ran insecure content from 'http://emptyorchestra.disqus.com/embed.js': this content should also be loaded over HTTPS.
```

**Comment by daveyarwood** [comment]
I don't think I can support https at the moment, especially now that I've CNAMEd my blog to http://blog.djy.io. If I ever do get an SSL cert set up, etc., I will take another look at loading disqus with `//:` instead of `http://`.
